controller_list:
  - name: /youbot/controller/youbot_trajectory/
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - virtual_theta
      - virtual_x
      - virtual_y