youbot:
    hardware_interface:
      loop_hz: 2
      joints:
        - arm_joint_1
        - arm_joint_2
        - arm_joint_3
        - arm_joint_4
        - arm_joint_5
        - virtual_x
        - virtual_y
        - virtual_theta

    controller:
      youbot_state:
        type: joint_state_controller/JointStateController
        publish_rate: 200

      youbot_trajectory:
        type: effort_controllers/JointTrajectoryController
        joints:
          - arm_joint_1
          - arm_joint_2
          - arm_joint_3
          - arm_joint_4
          - arm_joint_5
          - virtual_x
          - virtual_y
          - virtual_theta
        gains:
          arm_joint_1: {p: 62.0, i: 0.0, d: 4.5}
          arm_joint_2: {p: 62.0, i: 0.0, d: 4.5}
          arm_joint_3: {p: 62.0, i: 0.0, d: 4.5}
          arm_joint_4: {p: 62.0, i: 0.0, d: 4.5}
          arm_joint_5: {p: 62.0, i: 0.0, d: 4.5}
          virtual_x: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
          virtual_y: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
          virtual_theta: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
        velocity_ff:
          arm_joint_1: 8.0
          arm_joint_2: 8.0
          arm_joint_3: 8.0
          arm_joint_4: 8.0
          arm_joint_5: 8.0
          virtual_x: 1.0
          virtual_y: 1.0
          virtual_theta: 1.0
        constrains:
          goal_time: 10.0
          arm_joint_1:
            goal: 0.1
          arm_joint_2:
            goal: 0.1
          arm_joint_3:
            goal: 0.1
          arm_joint_4:
            goal: 0.1
          arm_joint_5:
            goal: 0.1
          virtual_x:
            goal: 0.5
          virtual_y:
            goal: 0.5
          virtual_theta:
            goal: 0.5

